### ISSUE TITLE
QC of DTI scans should skip B0 images for slice/TR wise abnormality plots

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#11]
Right now I believe it just assumes the first few volumes are b0, but it should probably consult the bval file. As it stands, the plots scale poorly because of the greater intensity of the included b0 slices: 

![example](http://snag.gy/LMYSY.jpg)

**Comment by josephdviviano** [comment]
Yeah, I think the best way would be some sort of A) configuration YAML file, or B) a command line argument where you can define the B0s, but I can see the number of commands at the command line becoming enormous over time, so the YAML file might be better? If you have a preference let me know.

**Comment by pipitone** [comment]
Why is a YAML file necessary? Couldn't we just look at the bvec file and skip those volumes that have a 0 length direction vector.

**Comment by josephdviviano** [comment]
Ah yeah that is a better idea :)

**Comment by josephdviviano** [comment]
Especially since they have shifted in the past over time...

**Comment by pipitone** [comment]
#datdatadrivenapproachtho

**Comment by josephdviviano** [comment]
![analytics-decision-making](https://cloud.githubusercontent.com/assets/4142570/7539203/67069a94-f573-11e4-9b54-1fc013257510.jpg)

**Comment by josephdviviano** [comment]
![dis_rgb-1024x362](https://cloud.githubusercontent.com/assets/4142570/7539206/6dca75c6-f573-11e4-9063-beb196df85a5.jpg)

**Comment by pipitone** [comment]
@josephdviviano completed this at e0613ee0e9bf02a8babf167fd304f8bdea55f7f4
