### ISSUE TITLE
qc.py trackback on run

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#14]
Run `qc.py`, get this: 

```
jp@riker:/archive/data-2.0/ASDD$ qc.py --datadir $PWD/data --qcdir $PWD/qc
Traceback (most recent call last):
  File "/archive/data-2.0/code/datman/bin/qc.py", line 811, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/qc.py", line 808, in main
    qc_folder(path, timepoint, qcdir, QC_HANDLERS) 
  File "/archive/data-2.0/code/datman/bin/qc.py", line 113, in qc_folder
    QC_HANDLERS[tag](fname, outputdir, pdf)
  File "/archive/data-2.0/code/datman/bin/qc.py", line 204, in fmri_qc
    pdf = find_epi_spikes(fpath, filename, pdf)
  File "/archive/data-2.0/code/datman/bin/qc.py", line 557, in find_epi_spikes
    while flag == 0:
UnboundLocalError: local variable 'flag' referenced before assignment
```

This is from the latest commit. I think @josephdviviano broke the build.

Suggest a commit that: 
- [ ] Adds a nose test that exposes this bug
- [x] A fix

**Comment by josephdviviano** [comment]
Hey I added a fix (just forgot to init a flag variable). Been pulled to the archive.

Could we look at how to build a test for this together? I can't really get my head around how to build tests except in very theoretical and simple cases.

**Comment by pipitone** [comment]
> Could we look at how to build a test for this together? I can't really
> get my head around how to build tests except in very theoretical and
> simple cases.

Thanks. For something like this, I'd start with just a simple
integration test in which you have a dummy image (something small,
ideally you'd create it in memory, but otherwise on disk), and call
find_epi_spikes() on it. 

The very simplest test, which would catch this bug, is just the test
that the function runs without raising any errors.

Ideally, you'd also have tests to to compare the output of the function
with some expected value. To do this for find_epi_spikes, you might have
to refactor the function a little, perhaps into two functions: one that
computes mean intensity slices and returns them as an array, and one
that plots them.

**Comment by pipitone** [comment]
We also might want to have a dummy set of study data (say, one or two
subjects) and build a mock run.sh script that quickly does all of the
steps of a real study's run.sh. We could then use this as a kind of
[smoke test](http://en.wikipedia.org/wiki/Smoke_testing_%28software%29)
before anything gets pushed.

**Comment by pipitone** [comment]
This issue is fixed. I'll create other issues for tests.
