### ISSUE TITLE
link.py does not use the mappings defined in scans.csv in some cases

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/datman#19]
Example case fails:
    source_name             target_name              PatientName             StudyID
    COGBY_CMH_27B034_01_02  COGBDY_CMH_27B034_01_02  COGBY_CMH_27B034_01_02  3785

link.py creates the following zip file:

    COGBY_CMH_27B034_01_02.zip

when it should be 

    COGBDY_CMH_27B034_01_02.zip

and makes me sob

suspicion: since COGBY_CMH_27B034_01_02 is 'appropriate', the mapping is not being applied.

**Comment by josephdviviano** [comment]
nm i just josephed all over the place :D

**Comment by pipitone** [comment]
![Oh you](http://static.fjcdn.com/pictures/Oh+you+oh_abef1c_3725180.jpg)
