### ISSUE TITLE
Change log in the study READMEs? 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#22]
This a question for discussion for @josephdviviano and @edickie. 

When I was more deeply involved with shepherding the DTI 3T data into `data-2.0` I kept a record of problems and changes we made to it over time in the `README.md` (with references to github issues where necessary). I thought this was a nice way of consolidating the history of the project in one place, in case someone else wanted to know what happened to a bit of data or wanted to see the issue history at a glance. If you look at it now, there are issues around previously missing data, data corruption and how we handled it, etc.  Basically, anything that causes us to change the `data/` folder I would record. 

My question to you all is, would you like to make this a standard practice across all of our projects? I recognise this practice is my slightly detail-oriented software dev side showing through, and that this level of detail may not be something you see the value in or be interested in recording in this way (since you're both likely more familiar with what record keeping /actually/ matters). 

As a concrete example, issue tigrlab/admin#266 is just about to be wrapped up. Do we close the issue and move on, or record our changes in the `COGBDY/README.md` for posterity?

**Comment by edickie** [comment]
Sounds like a good idea to me.

**Comment by josephdviviano** [comment]
Yes I agree, anything that is github issue worthy should be copied into the README.
