### ISSUE TITLE
Consolidate QC operations

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#34]
At the moment we have a few bits and pieces of QC that output in various places which can get missed, such as: 

1. bval/bvec checks for DTI scans (log file)
2. DICOM header checks (log file)
3. Check that all scans present per subject 
4. For EMP scans, a check whether behavioural data exists
4. Visual QC of scans

This ticket is about consolidating QC checks into the QC report where possible so that the humans can sign off/blacklist by looking in one place, and to keep the nightly run logs free of QC output (runtime errors only).

**Comment by pipitone** [comment]
A note about header checks: @josephdviviano @edickie discussed how this should be recorded and the solution is to 1) create one file per scan (all series) that contains all header differences, and 2) show per-series header differences in the consolidated QC file.

**Comment by pipitone** [comment]
Further conversation with @edickie about how to handle knowing when a QC doc is stale (and so needs a human to look at it and sign-off), there are two cases: 

1. The QC doc is first generated, and has never been signed-off on before. 
2. The QC doc is signed-off on already, but new data has arrived (e.g. new series have been exported, or a repeat scan for that time point is done). 

So, to handle these cases, `watqc` could list a subject as needing QC if the data in `data/nii` is newer than the QC doc, or the doc hasn't been signed off on at all. 

If we do this, then all of the QC components leading up the QC doc (bvec/bval/header/behavioural check/etc..) no longer need a blacklist: they just run all time since they're quick, and silently output to log files in the `qc/` folder. The `qc.py` stage simply looks to see if the qc doc exists, and creates one if it doesn't from those files and the data in `data/nii`. 

Thoughts?

**Comment by josephdviviano** [comment]
This makes a lot of sense to me. The other thing that is nice about this is that the individual QC stages become pretty basic tools for others to use (input --> output), and we can leave the QC.py part a tigrlab specific script that builds our webpages or whatever.

**Comment by pipitone** [comment]
PR #38 solves #1 and #2 above.

**Comment by josephdviviano** [comment]
Accomplished using `qcmon`.
