### ISSUE TITLE
dm-proc-imob blocks while preprocessing jobs complete

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#35]
Currently `dm-proc-imob` fires off a preprocessing job to the queue for each subject, and waits for those jobs to be completed before finishing. This is problematic if the queue is busy, since then the nightly data-2.0 run is held up (e.g. it's currently 4pm and the run is not yet 50% the way through the studies). 

I'm filing this issue so that we can come to some agreement about how to proceed. I can see a few ways forward: 

1. Live with it.
2. Submit the `dm-proc-imob` job itself, and let it submit jobs and hold, independently of run.sh
3. Break up `dm-proc-imob` into a pre-processing script stage (which gets submitted) and an export/analyse stage (which also gets submitted, holding on the subject's preprocessing stage being complete).

**Comment by josephdviviano** [comment]
I vote for 2 (simple change to run scripts). Breaking it up would be a lot more work, and this isn't a very portable script anyways.
