### ISSUE TITLE
dm-check-headers not reading StudyDescription properly for STOPPD

### ISSUE THREAD

**Issue by edickie** [TIGRLab/datman#41]
The qc pages are printing the error:
header StudyDescription, expected = STOP1MR, actual = [tolerance = None]

But if you run archive-manifest on the zips file you see that the StudyDescription is  STOP1MR for this participant...

archive-manifest.py 20151110_Ex04578_STOP1MR_STKR063.zip 
Path,PatientName,SeriesDescription,SeriesNumber,StudyDescription,StudyID
20151110_Ex04578_STOP1MR_STKR063/Ex04578_Se00001_3PlaneLocSSFSE,STOPPD_CMH_410039_01_01,3PlaneLocSSFSE,1,STOP1MR,4578

so some bug must not be reading the string in properly??

**Comment by josephdviviano** [comment]
Did we resolve what is causing this bug? In any case, there is no reason to compare the study description, because this changes for very uninteresting reasons.

**Comment by josephdviviano** [comment]
I've removed this from the checks we do.
