### ISSUE TITLE
dm-proc-freesurfer.py isn't analyzing the human phantom data from MRC

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/datman#43]
e.g. this subject `/archive/data-2.0/SPINS/data/nii/SPN01_MRC_P001_02` wont be run.

This is all I can find in the checklist:

```
SPN01_MRC_P003_02,,,,,> 1 _T1_ found
SPN01_MRC_P001_02,,,,,> 1 _T1_ found
SPN01_MRC_P002_02,,,,,> 1 _T1_ found
```

**Comment by edickie** [comment]
Fixed the arguments for dm-proc-freesurfer in run.sh
