### ISSUE TITLE
enigmadti silently ignores subjects with multiple DTI acquisitions

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#47]
For example, the first participant in DBDC has six DTI acquisitions. When `dm-proc-enigmadti.py` is run on the project, it silently does nothing (no jobs submitted, but some scripts are written out) when it should run once for each acquisition.

**Comment by edickie** [comment]
I would argue that we wouldn't want one spreadsheet of multiple enigma DTI outputs for each subject.. So engima DTI was written to only except one input DTI scan per subject (and write a note to he engima-checklist file if not).

To get engima output for multiple acquisition type you could make an output directory for each acquisition type, then make call each analysis separately with a filter argument...

**Comment by josephdviviano** [comment]
related to our discussion in the hallway:

there should be 2 scripts:
+ one that just runs the stock enigma DTI pipeline on any DTI file it is presented with.
+ one that scrapes ALL outputs to generate summary tables.

**Comment by josephmje** [comment]
I think this has been addressed in new enigma dti pipeline.
