### ISSUE TITLE
Clean up qc-html

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/datman#58]
Some issues that need work in qc-html:

1. The 'factor' functions are unused.
2. References to pdfs need to be removed, many comments are out of date, not sure if all imports are actually necessary anymore.
3. 'dry-run' option doesn't seem to stop anything from being created.
4. The database functionality may not work, needs to be fixed/removed if not.
5. All image creation related functions need to be moved into their own module

I'll handle this and create an automated test suite after finishing Colin's stuff.

**Comment by josephdviviano** [comment]
@DESm1th soon you won't even recognize `qc-html`...

**Comment by DESm1th** [comment]
Since you guys are rewriting this anyway, I've found a bug in qc-html's montage function that's kind of weird and needs to be fixed. 

When the montage function is called from dti_qc with this file /archive/data-2.0/ASDD/data/nii/ASDD_CMH_EF001_02/ASDD_CMH_EF001_02_01_DTI60-29-1000_07_Ax-DTI-60plus5-Nov2011.nii.gz  the B0 pic (or I guess any 3d pic) causes qc-html to crash with an index out of bounds error.

I've narrowed the cause down to the fact that numpy and the nifti header both think the first axis has a length of 72, but for whatever reason the first axis is actually 70 so the steps[i] call on the final iteration attempts to axis index 70, when it really goes from 0-69.

**Comment by josephdviviano** [comment]
Thanks Dawn,

That's useful. Can you determine if this is a problem in this code: https://github.com/josephdviviano/qcmon/blob/master/bin/qc-img

We're not using this for anything at the moment, but the montage function of `qc-html` (and all of datman, really) will soon be gone. All qc calculations will be done via `qcmon`.

**Comment by DESm1th** [comment]
Ok! I'll take a good look at it tomorrow with fresh eyes and let you know if it's an issue

**Comment by DESm1th** [comment]
qc-img does have that same problem. On line 159 steps[i] may feed a too large value in when indexing the 3d image array.

Is that script still a work in progress? It's missing all the import statements and stuff still. Also are all these scripts meant to be importable or will they be called as command line tools?

**Comment by DESm1th** [comment]
I did a little more digging. The reason this happens is because bounding box is resizing the first axis after steps was already calculated under an assumption that the first axis went to 0-72. Calculating the bounding box first fixes it.

**Comment by josephdviviano** [comment]
That's excellent, thanks. I filed a ticket about that here:

https://github.com/josephdviviano/qcmon/issues/5

`qc-img` and `qc-gif` are still WIP -- they're not important b/c they aren't going to be used for anything any longer (we're just using `payapa.js` and `slicer` for this sort of stuff going forward).
