### ISSUE TITLE
qc-dm-report.py is generating header differences, but is not putting them in the HTML report

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/datman#60]

**Comment by navonacalarco** [comment]
Thanks. I was just wondering if that might be so... :)

**Comment by josephdviviano** [comment]
Fixed and tested. Future header differences should appear directly in html reports.

See https://github.com/TIGRLab/datman/commit/7ccc5ae56bad015d53623448a31043dae78601ec and https://github.com/TIGRLab/datman/commit/994165391f9bb09cb206a60839622acb6bbed8e8
