### ISSUE TITLE
dm-proc-dtifit.py should flag no files found

### ISSUE THREAD

**Issue by colinhawco** [TIGRLab/datman#81]
I tried running dm-proc-dtifit.py on a data set on the SCC, and had made a mistake. None of the files had "DTI" in their file name.

It just returned a blank and did nothing. would be nice if it had a small amount of verbiosity, to for example say "XX DTI files found"

And that way a person running it manually will see if it misses a file, or if it returns 0 files found. 

I assume this would not be hard, but what do I know?

**Comment by josephdviviano** [comment]
Hi Colin, good idea. I'll add this to only be done if the `--debug` flag is used.

**Comment by josephdviviano** [comment]
fixed here https://github.com/TIGRLab/datman/commit/af3b712a490213498cf111254737cce66b73522c
